spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/develop
    username: junseok
    password: 1234qwer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MariaDBDialect
      connection:
        provider_disables_autocommit: true